### ISSUE TITLE
Windows Standalone Build Error ->  'WSA' does not exist in the namespace

### ISSUE THREAD

**Issue by WikkidEdd** [Azure/azure-remote-rendering#36]
After upgrading from SDK version 1.0.6 to 1.0.13 we've started getting a build error for our Windows Standalone builds:

error CS0234: The type or namespace name 'WSA' does not exist in the namespace 'UnityEngine' (are you missing an assembly reference?) 

This is caused by an un #if'd reference to the WSA namespace as a parameter of MainThreadInvoker.Invoke.

I'm a little unclear why the action in that function needs to be a `UnityEngine.WSA.AppCallbackItem`? It looks like it could just be a System.Action.

**Comment by jumeder** [comment]
Hi @WikkidEdd, sorry about that. I think you're right, the WSA reference is unnecessary there in any case. I'll let you know when we fixed it, shouldn't be too long.

**Comment by jumeder** [comment]
Hi again @WikkidEdd, we fixed this issue with the [latest release](https://github.com/Azure/azure-remote-rendering/releases/tag/1.0.15)!
